src/components/templates/LoginTemplate/LoginTemplate.stories.tsx, src/components/templates/LoginTemplate/LoginTemplate.tsx
초기 로그인 화면, 회원가입 직후 닉네임/프로필 사진 설정 화면, 2FA 인증 화면 등에서 사용할 수 있는 로그인 페이지 Template을 제작하였습니다.
Storybook 으로 렌더링 확인
[Material-ui Grid](https://material-ui.com/components/grid/), [Grid-interactive](https://material-ui.com/components/grid/#interactive)
close #15
=> Feat: 로그인 페이지 Template 제작

.env, package.json, src/App.tsx, src/components/pages/LoginPage/LoginPage.tsx, src/index.tsx, src/utils/hooks/useContext.tsx, src/utils/utils.ts, yarn.lock
- React의 Context API와 useReducer hook을 사용하여 App 전체의 상태 관리 로직을 작성하였습니다. 현재 state에 유저의 id가 존재하는지 확인하고, 존재하는 경우 메인 페이지, 존재하지 않으면 LoginPage 컴포넌트를 렌더링합니다(React-router 사용). 단, 메인 페이지 컴포넌트는 아직 구현되지 않았으므로 임시로 작성해 두었습니다.
- root path(``/``)로 접속할 때마다(=App 컴포넌트가 마운트 될 때마다) 세션 ID를 검증합니다. 세션이 살아있는 경우 API 서버에서 받아온 유저 정보를 state에 저장하고, 등록된 세션이 없는 경우 앱의 state를 초기화하여 로그인을 유도합니다.
- 현재 작업 단계에서 API 서버와 통신이 이루어지지 않기 때문에 코드를 임의로 작성한 부분이 몇 군데 있습니다. (App의 ``isLoading`` state+progress bar 등) 이 부분은 ``FIXME`` 처리 해두었으므로 추후 수정하겠습니다.
- 통신 에러 메시지를 보여주는 부분에서 Toast를 사용하면 좋을 것이라 판단해 react-toastify와 Material ui의 Snackbar 중 무엇을 도입할지 고민하였고, react-toastify를 도입하였습니다. UI 일관성을 고려하면 Material ui를 사용하는 것이 좋겠지만, react-toastify를 사용하면 부가적인 context 작성 및 다른 처리에 대한 고려 없이 toast를 간편하게 띄울 수 있다는 점이 큰 장점이라 보았습니다. 혹시 다른 의견이 있으시면 말씀해주세요!
``yarn …
=> Feat: App 상태 관리 로직 작성

src/components/atoms/DigitInput/DigitInput.stories.tsx, src/components/atoms/DigitInput/DigitInput.tsx
- 2FA DigitInput verifiaction code를 제작한다.
- [Slack email verification code box 디자인](https://blog.kakaocdn.net/dn/dC0G6u/btqw2mqwH84/mhLRfgjhGHsaZBPNkjFqb1/img.png)을 참고하여 제작
- 숫자 하나만 입력가능
- **질문:** 박스의 크기와 숫자의 크기를 보시고, 조금 더 예쁘게 만들 수 있다면 피드백을 받고 수정해보도록 하겠습니다!
각각 Firefox, Chrome, Safari로 Storybook으로 랜더링, 숫자 하나만 입력 확인
[slack email code](https://blog.kakaocdn.net/dn/dC0G6u/btqw2mqwH84/mhLRfgjhGHsaZBPNkjFqb1/img.png)
[material-ui input](https://material-ui.com/api/input/)
close #35
=> Feat: 2FA Digit input code 제작

src/components/atoms/Button/Button.tsx, src/components/atoms/Input/Input.tsx, src/components/molecules/Dialog/Dialog.stories.tsx, src/components/molecules/Dialog/Dialog.tsx
- 범용으로 사용될 수 있는 Dialog component를 제작했습니다.
- 2FA 등록 화면에서 QR코드 등록 확인 용도로 사용
- 프로필 수정, 2FA 여부 변경 등의 기능에 Dialog를 사용하면 새 페이지를 만들지 않고도 구현 가능
Storybook으로 렌더링 확인
- [Material UI Dialogs](https://material-ui.com/components/dialogs/)
close #41
=> Feat: Dialog component 제작

src/App.tsx, src/components/atoms/DigitInput/DigitInput.tsx, src/components/pages/MFAPage/MFAPage.stories.tsx, src/components/pages/MFAPage/MFAPage.tsx, src/components/pages/MFARegisterPage/MFARegisterPage.stories.tsx, src/components/pages/MFARegisterPage/MFARegisterPage.tsx, src/components/pages/RegisterPage/RegisterPage.tsx
피어 프로그래밍으로 구현하였습니다.
- 2FA를 등록할 수 있는 페이지(`MFARegisterPage`), 2FA 인증을 진행할 수 있는 페이지(`MFAPage`) 컴포넌트를 작성하였습니다. 변수 이름 첫글자에 숫자를 사용할 수 없기 때문에 2FA 대신 MFA라는 명칭을 사용하였습니다.
- 2FA는 google authenticator(=google OTP) 모바일 어플리케이션을 이용하여 진행합니다. 회원가입 시 2FA를 활성화하면 QR코드 등록 화면으로 이동하며, QR코드를 등록한 후 로그인을 시도하면 2FA 인증 화면에서 6자리 OTP 코드를 입력받도록 되어 있습니다.
<br>
- ~**개선 요구사항**: 지금은 `MFARegisterPage`에서 2FA 등록 버튼을 누르면 사용자가 QR코드를 스캔하였는지 여부를 확인하지 않고 2FA 등록을 종료합니다. 그런데 **사용자가 QR코드를 스캔하지 않고 2FA 등록 버튼을 누를 가능성**이 있기 때문에 이 부분에 개선이 필요할 것 같습니다. QR코드 등록이 정상적으로 완료되었는지 확인하는 API 구현을 백엔드 팀에 요청하고, 2FA 등록 시 해당 API와 요청-응답으로 확인하는 방법으로 개선할 수 있을 듯합니다.  
추가 API 구현 없이 프론트엔드 단에서 해결할 방법(App.tsx의 useEffect 응답 결과로 판단하여 history 조작)도 고민해 보았으나, history 관련 로직이 꼬여서 해당 로직을 백엔드로 옮긴 상황이기 때문에 프론트엔드에 비슷한 로직을 도입하면 다시 의도치 않은 동작을 하게 될 것 같습니다. 이렇게 구현하는 것이 최선이 아닐까 …
=> Feat: 2FA Page 제작

src/App.tsx, src/components/pages/MFARegisterPage/MFARegisterPage.tsx, src/components/pages/RegisterPage/RegisterPage.tsx
회원가입 완료 시 '회원가입이 완료되어 로그인 화면으로 돌아갑니다. 서비스를 이용하시려면 로그인 해주세요.'라는 내용의 Dialog가 표시되도록 하였습니다. 
- Storybook 렌더링 확인
- docker-compose로 API 서버와 연동하여 회원가입 후 Dialog 정상 표시 확인
- [material-ui Drawer - findDOMNode is deprecated in StrictMode](https://stackoverflow.com/questions/61220424/material-ui-drawer-finddomnode-is-deprecated-in-strictmode)
Material UI에서 제공하는 Modal 관련 컴포넌트(위 질문의 `Drawer`, 저희 프로젝트의 `Dialog` 등)가 [deprecated된 `findDOMNode`](https://ko.reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage)를 사용하고 있었습니다. 이 부분은 React.StrictMode에서 error로 console에 표시되는데, [이 답변](https://stackoverflow.com/a/64135466/13614207)을 참고하여 console error를 방지할 수 있었습니다. 사람들이 많이 사용하는 프레임워크는 최신 기술을 사용하고 있을 것이라 막연히 생각했는데 꼭 그렇지는 않다는 것을 깨달았고, 사용하는 기술에 대해 정확히 파악하는 것이 정말 중요하다는 것을 다시금 깨달았습니다.
close #43
=> Feat: 회원가입 완료 시 안내 Dialog 추가

src/components/atoms/Avatar/Avatar.tsx, src/components/atoms/Button/Button.tsx, src/components/molecules/UserProfile/UserProfile.stories.tsx, src/components/molecules/UserProfile/UserProfile.tsx, src/components/organisms/ProfileCard/ProfileCard.stories.tsx, src/components/organisms/ProfileCard/ProfileCard.tsx, src/types/User.ts
- `UserProfile` component(molecules)를 작성했습니다. 유저의 avatar, name, status, 전적을 표시해줍니다. 원래는 ProfileCard 컴포넌트 내부에 작성하려 했던 내용이나, (1) 친구 목록이나 차단 목록에서 본 컴포넌트를 재사용할 수 있지 않을까 하여 (2) ProfileCard component 내부에 너무 많은 내용이 들어가는 것이 아닌지 고민이 되어 molecules 수준의 컴포넌트로 분리해보았습니다.
- `ProfileCard` component(organisms)를 작성했습니다. Page 단위에서 API로부터 얻은 userInfo 객체를 props로 내려보내주면 context를 통해 본인 여부를 판단하고, 본인 프로필의 경우 정보 수정 버튼, 타인 프로필의 경우 친구 추가/유저 차단/DM/매치 초대 버튼을 보여주게 됩니다. 본 컴포넌트가 자체 status를 가지지는 않으므로 story는 임의의 userInfo 객체를 제공하는 식으로 작성하였습니다.
- Storybook으로 렌더링 확인
- [Material UI Grid](https://material-ui.com/components/grid)
close #22
=> Feat: ProfileCard component 제작

src/components/pages/MFAPage/MFAPage.tsx, src/components/pages/MFARegisterPage/MFARegisterPage.tsx
윈도우 크기를 크게 하면 MFAPage, MFARegisterPage의 레이아웃이 깨지던 현상을 개선했습니다.
- **문제가 발생했던 원인**: LoginTemplate이 Grid를 기반으로 작성되어 있기 때문에 LoginTemplate에 props로 넘겨준 ReactNode들은 따로 Grid 속성을 주지 않으면 item으로 간주됩니다. MFAPage, MFARegisterPage에서 Input props로 넘겨준 node 또한 Grid 속성 없이 `Fragment`로 감싸져있어 내부 컴포넌트 두 개가 각각 Grid의 item으로 간주되고 있었습니다. LoginTemplate의 Input props가 위치하는 container Grid는 기본적으로 `direction="row"` 속성을 가지는데, 이로 인해 윈도우 크기가 커지면 row로 정렬되었던 것입니다.
- **해결한 방법**: Input으로 넘길 컴포넌트를 Fragment 대신 `direction="column" alignItems="center"`속성을 가지는 container Grid로 감싸주었습니다.
- Storybook으로 렌더링 확인, 윈도우 크기를 변경하며 레이아웃 확인
x
close #48
=> Fix: MFAPage, MFARegisterPage의 레이아웃이 깨지는 현상 개선

src/components/Chat.stories.tsx, src/components/atoms/ChatInput/ChatInput.stories.tsx, src/components/atoms/ChatInput/ChatInput.tsx, src/components/atoms/List/List.tsx
채팅 기능을 위한 기반 작업을 진행하였습니다.
- List 컴포넌트를 채팅에서도 사용할 수 있도록 확장
- `reverse` props를 추가하면 Grid의 direction이 `column-reverse`로 설정되도록 구현
- ChatInput 컴포넌트 제작
- Story 작성 (Tests-Chat-Chat Test)
<br>
- 추후 채팅 컴포넌트 구현 시 고려하면 좋을 것 같은 점
`<ListItem />`  컴포넌트에서는 한국어의 경우 띄어쓰기 없이 width 이상의 글을 써도 자동 줄바꿈이 되는데 영어는 자동 줄바꿈이 되지 않았습니다. 채팅용 말풍선(?) 컴포넌트를 구현할 때에는 [`word-break: break-all;` 같은 속성](https://developer.mozilla.org/ko/docs/Web/CSS/word-break)을 넣어 줄바꿈까지 고려해주면 좋을 것 같습니다.
-
close #75
=> Feat: 채팅 기능을 위한 기반 작업

src/components/organisms/ProfileCard/ProfileCard.tsx, src/components/pages/CommunityPage/CommunityPage.tsx, src/utils/hooks/useIntersect.ts
- relation이 'NONE'인 사용자의 ProfilePage에서 친구/차단 버튼이 보이지 않는 문제
-> CommunityPage의 전체 유저 목록에서 친구/차단 버튼을 보이지 않게 하기 위해 적용한 로직이 잘못되어 있었습니다. 그래서 해당 부분에 profile 여부를 판별하는 로직을 추가하였습니다.
- isListEnd가 true여도 렌더링을 계속하여 시도하는 문제
-> isListEnd가 true이면 intersect 요소를 렌더링하지 않도록 변경하여 해결하였습니다.
- 친구 목록에서 intersection이 먼저 일어나면 요청 목록이 친구 목록을 뒤집어씌워서 친구 목록을 확인할 수 없게 되는 문제
-> isListEnd의 초기값을 true로 설정하고, 요청 목록을 불러온 뒤 isListEnd를 false로 변경해 intersection이 발생하도록 하여 해결하였습니다.
- 친구 목록이 개발자 도구 등으로 가려져있을 경우 intersection threshold가 커서 fetch가 일어나지 않는 문제
-> 이런 경우를 고려하여 threshold 값을 감소시켜주었습니다.
API 연동 테스트 완료
fix #83
=> Fix: CommunityPage의 오류 수정

src/components/atoms/Avatar/Avatar.tsx, src/components/organisms/ChatMessage/ChatMessage.stories.tsx, src/components/organisms/ChatMessage/ChatMessage.tsx, src/types/Chat.ts
채팅 UI에서 말풍선으로 사용할 수 있는 ChatMessage 컴포넌트를 제작하였습니다.
- Avatar에 onClick 속성을 추가하고, onClick props가 존재하는 경우 hover시 Avatar의 opacity가 변경되도록 하였습니다.
- 유저 정보를 기반으로 말풍선, Avatar, name, 메시지를 보낸 시간(createdAt)을 렌더링합니다.
- me 속성이 있으면 Avatar, name을 그리지 않습니다.
- userRole이 OWNER나 ADMIN이면 Badge를 렌더링합니다.
API가 확정되지 않은 상태이므로 Draft PR으로 올립니다!
- 왕관 모양 [Material Icon](https://material-ui.com/components/material-icons/#material-icons)이 존재하지 않아 임의로 shield icon을 채택해 보았는데 어떤지 의견 부탁드립니다! 저도 이게 썩 마음에 들지는 않는데 이게 좋겠다 싶은 걸 못 찾겠더라고요...
close #86
=> Feat: ChatMessage component 제작

src/components/organisms/ChannelListItem/ChannelListItem.stories.tsx, src/components/organisms/ChannelListItem/ChannelListItem.tsx, src/types/Channel.ts, src/types/Chat.ts
ChannelListItem 제작
- 입장한 방이면 ``unreads`` count가 보임
- ``admin``/``owner``면 채널 참가, 채널 관리 두 버튼이 보임
- skeleton UI 추가
- ``/type/Chat.ts`` 다른 브랜치에서 가져옴
1. ``Channel`` 권한 관련 코드를 짜기 편하게 하기 위해 ``src/types/Chat.ts``에서 아무관계도 없는 ``NONE``을 추가했는 데, 이렇게 하지 말고 **FE**에서 정제한 다른 ``type``을 따로 만드는 게 나은 지 궁금합니다.
- 또한 ``isLocked``라는 비밀번호 방인지 확인하는 ``type``을 넣었습니다. 비밀번호가 있으면 ``true``, 없으면 ``false``로 생각하고 코드를 작성했습니다.
2. ``ChannelListItem`` 가장 앞쪽에 ``updatedAt``을 넣었습니다. 나중에 업데이트 시간 순서대로 ``ChannelListItem``을 정렬하려고 하는 데, 어떻게 생각하시는 지 궁금합니다.
3. ``Buttons component``를 너무 하드코딩식으로 짰고 storybook의 코드도 너무 원시적으로 짰습니다. 이것을 개선할 때 어떻게 개선해야할 지 힌트 부탁드립니다. ㅠㅠ 뭔가 잘못되었다는 것은 알겠지만, 어떻게 개선해야할 지 혼자 고민을 너무 오래 하게 되어 @hyo-choi님의 혜안으로 보시고 알려주셨으면 좋겠습니다.
4. 그 외에도 API와 연결했을 때 미리 ``Dialog``를 연결하는 것, ``DMListItem``과의 공통적인 것을 어떻게 고려해야하는 지 궁금합니다. …
=> Feat: ChannelListItem 제작

src/components/atoms/Input/Input.tsx, src/components/organisms/ChannelInfoForm/ChannelInfoForm.stories.tsx, src/components/organisms/ChannelInfoForm/ChannelInfoForm.tsx
`Channel Page`에서 `User`가 `Channel`을 추가할 때, 사용되는 양식을 제작했습니다. `Channel`을 **공개/비공개**로 만들 수 있도록 만들었고, **공개**로 선택했을 경우, `Channel` 제목을 _영문+숫자 5-25자_ 로 만들면 `Channel form`을 제출할 수 있게 만들었습니다. **비공개**로 했을 경우, 비밀번호 양식을 _영문+숫자 4-12자_ 로 맞춰줘야합니다. `Channel form`을 만족하는 내용을 적어주면, `채널 만들기` 버튼이 활성화됩니다.  
[Dialog](https://material-ui.com/api/dialog/), [UserInfoForm](https://github.com/404-DriverNotFound/frontend-b/blob/feat/Page-Profile%2347/src/components/organisms/UserInfoForm/UserInfoForm.tsx), [ProfilePage](https://github.com/404-DriverNotFound/frontend-b/blob/feat/Page-Profile%2347/src/components/pages/ProfilePage/ProfilePage.tsx)
close #63
=> Feat: ChannelInfoForm Component 제작

src/components/organisms/ChannelUserListItem/ChannelUserListItem.stories.tsx, src/components/organisms/ChannelUserListItem/ChannelUserListItem.tsx, src/types/Chat.ts
ChannelPage의 Channel User List에 사용될 ChannelUserListItem component를 제작했습니다.
OWNER와 ADMIN은 각각 허용된 권한을 가지고 ChannelUserList를 볼 수 있으며 허용된 권한에 따라 ChannelUserListItem component가 버튼들을 다르게 구성해줍니다.
> NOTE: 이 component에서 새롭게 추가된 props인 myRole은 상위 component에서 가공 후 넘겨줘야합니다.
[DMListItem](https://github.com/404-DriverNotFound/frontend-b/pull/91)
close #95
=> Feat: ChannelUserListItem component 제작

src/components/organisms/PlayerProfile/PlayerProfile.stories.tsx, src/components/organisms/PlayerProfile/PlayerProfile.tsx
GamePlayPage에서 Player의 아이디, 아바타, 전적을 알 수있도록 하는 Card를 만들었습니다.
ListItem으로 만들어져있고, UserInfoType에 win, lose의 property를 추가하여 [UserGameInfoType](https://github.com/404-DriverNotFound/frontend-b/compare/feat/component-PlayerProfile%2378?expand=1#diff-02527bcb476ee07f0519909437359ae42f9f1d5b6854a4521f82f185a3be6b2aR10)를 임시로 만들었습니다. 나중에 API가 완성되면 이에 따라 수정이 필요할 것같습니다.
- Storybook으로 랜더링 확인
.
close #78
=> Feat: PlayerProfile component 제작

src/App.tsx, src/components/molecules/GameOptionCard/GameOptionCard.tsx, src/components/pages/GamePage/GamePage.stories.tsx, src/components/pages/GamePage/GamePage.tsx
GamePage에서 Main이 되는 Page를 제작했습니다. 유저가 Classic Game, Speed Game, Reverse Game, WatchGame을 선택해서 해당 페이지에 접속할 수 있도록 GameOptionCard를 정리해서 넣었습니다.
현재 Classic Game, Speed Game, Reverse Game, WatchGame들이 완성되지 않았으므로 임시로 랜더링하도록 했습니다.
예시: `<Route exact path={CLASSIC_PLAY_PATH} render={() => <h1>Classic play</h1>} />`
CommunityPage, ChannelPage과의 통일성을 위해 흰색 바탕안에 GameOptionCard를 넣었습니다.
close #29
=> Feat: GamePage component 제작

src/components/organisms/GameListItem/GameListItem.stories.tsx, src/components/organisms/GameListItem/GameListItem.tsx, src/components/pages/GamePage/GamePage.tsx, src/components/pages/GameWatchPage/GameWatchPage.stories.tsx, src/components/pages/GameWatchPage/GameWatchPage.tsx, src/types/Match.ts
현재 관전 가능한 게임 목록을 가져오는 GameWatchPage를 제작했습니다. GameListItem의 리스트를 All, Ladder, Exhibition에 따라서 보여줍니다. 
Pagination을 할 때 유저가 덜 지루하도록 GameListItem에 GameListItemSkeletonUI component를 추가했습니다!
- 관전을 위해 GameListItem을 클릭했을 때 이미 게임이 끝난 경우에 어떤 식으로 경고 메시지 또는 안내 메시지를 보낼 지에 대해서는 고려 안되어 있습니다.
- 이 점은 게임을 구현하고 나서 어떻게 이 점을 해결할 지 결정해야하는 부분일 것같습니다.
[CommunityPage PR](https://github.com/404-DriverNotFound/frontend-b/pull/70)
close #100
=> [Feat] GameWatchPage component 제작

src/utils/hooks/useAppContext.tsx
하나의 DM이 모든 DMListItem을 갱신하는 문제를 해결했습니다.
상태 관리 로직에서 채팅 중인 방/채팅 중이 아닌 방/map에 해당되는 방의 case를 잘못 나누어서 발생한 문제였습니다.
map에 해당되지 않는 방은 현재 상태를 유지하도록 하고, map에 해당되는 방만 latestMessage를 갱신하도록 하여 해결하였습니다.
.
fix #103
=> Fix: 하나의 DM이 모든 DMList를 갱신하는 문제 해결

src/App.tsx, src/components/pages/MFAPage/MFAPage.tsx
본 PR은 @PennyBlack2008 님과 VSCode LiveShare로 함께 작업하였습니다.
2FA 인증이 되지 않은 상태에서도 App.tsx에서 /blocks에 GET 요청이 보내지고 있었는데 이 때 발생하는 403 Forbidden 에러로 인해 앱에서 로그아웃되어 로그인 로직이 동작하지 않았습니다.
2FA 인증이 되지 않은 유저는 /blocks 등에 GET 요청을 보내지 못하도록 하고, 인증 이후 앱을 새로 mount(reload)하여 문제를 해결하였습니다.
fix #102
=> Fix: 2FA 회원가입 후 로그인이 되지 않는 문제 해결

src/components/pages/ProfilePage/ProfilePage.tsx, src/types/Game.ts
MatchHistory List와 Achievements List를 구현했습니다. MatchHistory List는 페이지네이션이 구현된 ChannelPage, GameWatchPage 등을 참고해서 만들었습니다. Achievements List는 페이지네이션 없이 구현했습니다.
Achievements List에서 GET 응답을 받는 동안 AchieveListItemSkeleton을 적용했는 데, 속도가 너무 빨라서 잘 안보입니다. 그래서 setTimeout을 적용시킬지 고민했으나 setTimeout은 적용하지 않았습니다.
.
issue #74의
=> Feat: ProfilePage 전적, 업적 리스트 구현

src/components/molecules/GameOptionCard/GameOptionCard.tsx, src/components/organisms/GameListItem/GameListItem.tsx, src/components/organisms/MatchListItem/MatchListItem.tsx
Firefox에서 drop-shadow css 적용 규칙이 Chrome, Safari와 다른 부분이 있었습니다. Chrome과 Safari와 같은 규칙으로 적용하면 이미지에 drop-shadow가 완전히 가려집니다. 그래서 Firefox에서만 drop-shadow 위치를 미세하게 다르게 해줬고 Chrome, Safari와 같은 이미지 스타일을 얻을 수 있었습니다.
Firefox, Chrome으로 APP실행하여 확인했습니다.
[target only firefox](https://www.geeksforgeeks.org/targeting-only-firefox-with-css/)
fix #113
=> Fix: Firefox에 drop-shadow 스타일 별도 적용

src/components/pages/ChannelManagePage/ChannelManagePage.tsx, src/components/pages/ChannelPage/ChannelPage.tsx, src/components/pages/ChatPage/ChatPage.tsx, src/components/pages/CommunityPage/CommunityPage.tsx, src/components/pages/DMPage/DMPage.tsx, src/components/pages/GameWatchPage/GameWatchPage.tsx, src/components/pages/ProfilePage/ProfilePage.tsx
#115 issue에 작성한 것과 같은 문제가 있어, 채팅 페이지를 이동할 때 page를 -1, isChatEnd를 true로 세팅한 후 page 값이 -1으로 바뀐 것을 확인한 뒤 목록을 로딩하도록 로직을 변경하였습니다. 
- 제가 확인한 바로는 전과 같은 문제가 발생하지 않았으나, 혹시라도 @PennyBlack2008 님의 환경에서 문제가 발생하지는 않는지 확인 부탁드립니다.
- 추가로 infinite scroll에 사용되는 callback 함수 내부 setTimeout의 시간을 기존의 250ms에서 10ms로 조정했는데, 관련된 문제는 없는지 확인 부탁드립니다.
fix #115
=> Fix: ChatPage에서 채팅 목록을 정상적으로 로딩하지 못하는 문제 해결
